catalog:
  '@antfu/eslint-config': ^5.4.1
  '@iconify-json/ri': ^1.2.7
  '@nuxt/eslint': 1.9.0
  '@nuxt/icon': ^2.2.0
  '@unocss/eslint-plugin': ^66.6.0
  '@unocss/nuxt': ^66.6.0
  '@unocss/preset-wind4': ^66.6.0
  eslint: ^9.39.2
  nuxt: ^4.2.2
  unocss: ^66.6.0
  vue: ^3.5.26
  vue-router: ^4.6.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
